export enum JobStatus {
  CREATED = "CREATED",
  POSTED = "POSTED",
  VIEWED = "VIEWED",
  REQUESTED = "REQUESTED",
  ACCEPTED = "ACCEPTED",
  COMPLETED = "COMPLETED",
  NO_SHOW = "NO_SHOW",
  NOT_FILLED = "NOT_FILLED",
}
